document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.title-container")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-search-bar")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-search-bar > div > div")
document.querySelector("#searchService")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-search-bar > div > div > div")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-search-bar > div > div > div > div")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-search-bar > div > div > div > div > button")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-search-bar > div > div > div > div > button > span")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(1)")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(1) > button")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(1) > button > span")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(2)")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(2) > button")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(2) > button > span")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(3)")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(3) > button")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(3) > button > span")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(4)")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(4) > button")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.search-container > div.column.column-chips > div:nth-child(4) > button > span")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1)")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.first-row")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.first-row > div")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.first-row > div > span.sc-jRQAMF.dIHgvr.pulso-icon.pulso-icon--small.rdicon-coin-transfer")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.first-row > div > span.price-time.price")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.first-row > div > span.sc-jRQAMF.dIHgvr.pulso-icon.pulso-icon--small.rdicon-clock")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.first-row > div > span.price-time.time")
document.querySelector("#__next > body > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.title-description")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.title-description > h2")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.title-description > p")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.buttons-footer")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.buttons-footer > button.sc-gsDJrp.hHcHMe.pulso-button.pulso-button--primary.pulso-button--small")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.buttons-footer > button.sc-gsDJrp.hHcHMe.pulso-button.pulso-button--primary.pulso-button--small > span")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.buttons-footer > button.sc-gsDJrp.deNlPz.pulso-button.pulso-button--white.pulso-button--small")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(1) > div.buttons-footer > button.sc-gsDJrp.deNlPz.pulso-button.pulso-button--white.pulso-button--small > span")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(2)")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(2) > div.first-row")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(2) > div.first-row > div")
document.querySelector("#__next > main > div > div.SearchFilterServicesstyles__SearchFilterServicesStyles-fopbmu-0.dlBWSp > div.results-container > div > div > div.cards-service > div:nth-child(2) > div.first-row > div > span.sc-jRQAMF.dIHgvr.pulso-icon.pulso-icon--small.rdicon-coin-transfer")



